package service

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	aferrors "github.com/tobiasosborne/vibefeld/internal/errors"
	"github.com/tobiasosborne/vibefeld/internal/ledger"
	"github.com/tobiasosborne/vibefeld/internal/state"
	"github.com/tobiasosborne/vibefeld/internal/types"
)

// AmendDepsManifestSchemaVersion is the only schema_version value this build
// accepts for an amend-deps manifest.
const AmendDepsManifestSchemaVersion = 1

// AmendDepsManifestItem is one edge correction in an amend-deps manifest. It
// mirrors the single-command flags; OperationID is generated by --dry-run and
// kept so the real run (and a crash recovery) recognises already-applied items.
type AmendDepsManifestItem struct {
	Node            string   `json:"node"`
	Add             []string `json:"add,omitempty"`
	Remove          []string `json:"remove,omitempty"`
	AddValidated    []string `json:"add_validated,omitempty"`
	RemoveValidated []string `json:"remove_validated,omitempty"`
	Reopen          bool     `json:"reopen,omitempty"`
	ExpectHash      string   `json:"expect_hash,omitempty"`
	Strict          bool     `json:"strict,omitempty"`
	Owner           string   `json:"owner"`
	Reason          string   `json:"reason"`
	OperationID     string   `json:"operation_id,omitempty"`
}

// AmendDepsManifest is the top-level document accepted by
// `af amend-deps --file`. Items are applied in file order, one commit each.
type AmendDepsManifest struct {
	SchemaVersion int                     `json:"schema_version"`
	Items         []AmendDepsManifestItem `json:"items"`
}

// ParseAmendDepsManifest decodes and validates raw manifest bytes. Any failure
// here is "file-invalid": nothing is attempted.
func ParseAmendDepsManifest(data []byte) (*AmendDepsManifest, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var m AmendDepsManifest
	if err := dec.Decode(&m); err != nil {
		return nil, aferrors.Newf(aferrors.AMEND_DEPS_FILE_INVALID, "amend-deps manifest is not valid JSON: %v", err)
	}
	if dec.More() {
		return nil, aferrors.New(aferrors.AMEND_DEPS_FILE_INVALID, "amend-deps manifest contains trailing content")
	}
	if m.SchemaVersion != AmendDepsManifestSchemaVersion {
		return nil, aferrors.Newf(aferrors.AMEND_DEPS_FILE_INVALID,
			"unsupported schema_version %d (expected %d)", m.SchemaVersion, AmendDepsManifestSchemaVersion)
	}
	for i, item := range m.Items {
		if strings.TrimSpace(item.Node) == "" {
			return nil, aferrors.Newf(aferrors.AMEND_DEPS_FILE_INVALID, "item %d: node is required", i)
		}
		if _, err := types.Parse(item.Node); err != nil {
			return nil, aferrors.Newf(aferrors.AMEND_DEPS_FILE_INVALID, "item %d: invalid node %q: %v", i, item.Node, err)
		}
	}
	return &m, nil
}

// MarshalIndent renders the manifest, including any operation ids assigned by a
// dry run, so the CLI can write the completed manifest back to disk.
func (m *AmendDepsManifest) MarshalIndent() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

// EnsureOperationIDs assigns a fresh operation id to every item that lacks one
// and reports whether any id was generated. A dry run calls this so the ids are
// persisted; a real run calls it too so an id-less manifest still gets one (a
// later --resume can then recognise it).
func (m *AmendDepsManifest) EnsureOperationIDs() bool {
	changed := false
	for i := range m.Items {
		if m.Items[i].OperationID == "" {
			m.Items[i].OperationID = generateDepsOperationID()
			changed = true
		}
	}
	return changed
}

// AmendDepsManifestStatus is the per-item report. Status is one of
// "applied", "applied(already)", "unchanged", "rejected:<code>" or
// "blocked:<code>".
type AmendDepsManifestStatus struct {
	Node             string   `json:"node"`
	OperationID      string   `json:"operation_id,omitempty"`
	Status           string   `json:"status"`
	Seq              int      `json:"seq,omitempty"`
	OldHash          string   `json:"old_hash,omitempty"`
	NewHash          string   `json:"new_hash,omitempty"`
	Reopened         bool     `json:"reopened,omitempty"`
	Added            []string `json:"added,omitempty"`
	Removed          []string `json:"removed,omitempty"`
	AddedValidated   []string `json:"added_validated,omitempty"`
	RemovedValidated []string `json:"removed_validated,omitempty"`
	Detail           string   `json:"detail,omitempty"`
	Reverify         bool     `json:"reverify,omitempty"`
	Reason           string   `json:"reason,omitempty"`
}

// AmendDepsReverify is one line of the re-verification work list: a node that
// is pending because it was reopened and must be re-accepted through
// `af verdicts apply`.
type AmendDepsReverify struct {
	Node    string `json:"node"`
	NewHash string `json:"new_hash"`
	Reason  string `json:"reason"`
}

// AmendDepsManifestReport is the full per-item report plus the aggregate
// counts used to choose the exit code (0/5/6/7, exactly as af verdicts apply).
type AmendDepsManifestReport struct {
	SchemaVersion int                       `json:"schema_version"`
	Items         []AmendDepsManifestStatus `json:"items"`
	Applied       int                       `json:"applied"`
	Unchanged     int                       `json:"unchanged"`
	Rejected      int                       `json:"rejected"`
	Blocked       int                       `json:"blocked"`
	Aborted       bool                      `json:"aborted,omitempty"`
	AbortReason   string                    `json:"abort_reason,omitempty"`
	Reverify      []AmendDepsReverify       `json:"reverify,omitempty"`
}

func (r *AmendDepsManifestReport) record(status *AmendDepsManifestStatus) {
	r.Items = append(r.Items, *status)
	switch {
	case status.Status == AmendDepsApplied || status.Status == "applied(already)":
		r.Applied++
	case status.Status == AmendDepsUnchanged:
		r.Unchanged++
	case strings.HasPrefix(status.Status, "blocked"):
		r.Blocked++
	default:
		r.Rejected++
	}
}

// exitError picks the AFError reporting the aggregate outcome; nil means the
// generic success outcome (exit 0). The tiers mirror `af verdicts apply`: an
// all-unchanged batch is its own clean no-op (exit 7), a batch with zero
// applied items is none-applied (exit 6), and a batch with some applied and
// some rejected/blocked is partial (exit 5). An empty manifest is none-applied
// (exit 6), matching verdicts apply rather than silently succeeding.
func (r *AmendDepsManifestReport) exitError() error {
	total := len(r.Items)
	if total == 0 {
		return aferrors.Newf(aferrors.AMEND_DEPS_NONE_APPLIED, "manifest has no items")
	}
	if r.Unchanged == total {
		return aferrors.Newf(aferrors.AMEND_DEPS_ALL_UNCHANGED, "all %d item(s) unchanged", total)
	}
	if r.Applied == 0 {
		return aferrors.Newf(aferrors.AMEND_DEPS_NONE_APPLIED, "0 of %d item(s) applied", total)
	}
	if r.Rejected == 0 && r.Blocked == 0 {
		return nil
	}
	return aferrors.Newf(aferrors.AMEND_DEPS_PARTIALLY_APPLIED, "%d of %d item(s) applied", r.Applied, total)
}

// DryRunAmendDepsManifest validates every item against the current state
// without writing anything, assigns operation ids to items lacking one, and
// returns the per-item plan (edge diff, resulting hash, rejection path). The
// caller is expected to persist the mutated manifest so the ids survive.
//
// Each successfully planned event is applied to the in-memory state before the
// next item is planned, so hashes, no-op decisions and cycle/scope verdicts
// match the real run (which reloads state after every commit) item for item.
func (s *ProofService) DryRunAmendDepsManifest(m *AmendDepsManifest) (*AmendDepsManifestReport, error) {
	st, err := s.LoadState()
	if err != nil {
		return nil, err
	}
	m.EnsureOperationIDs()
	report := &AmendDepsManifestReport{SchemaVersion: AmendDepsManifestSchemaVersion}
	report.Items = make([]AmendDepsManifestStatus, 0, len(m.Items))
	for _, item := range m.Items {
		status, plan := s.planManifestItem(st, item)
		report.record(&status)
		if status.Reverify {
			report.Reverify = append(report.Reverify, AmendDepsReverify{Node: status.Node, NewHash: status.NewHash, Reason: item.Reason})
		}
		// Advance the in-memory state so the next item sees this item's
		// effect, exactly as the real run's next commit would.
		if plan.Event != nil {
			if err := state.Apply(st, plan.Event); err != nil {
				return nil, fmt.Errorf("dry run: applying planned event for %s: %w", item.Node, err)
			}
			if carrier, ok := plan.Event.(interface{ GetOperationID() string }); ok {
				st.RecordOperation(carrier.GetOperationID(), operationRecordForEvent(st, plan.Event))
			}
		}
	}
	return report, nil
}

// ApplyAmendDepsManifest applies every item in file order, one commit per item,
// never reordering. A blocked or rejected item does not stop the batch; a
// concurrent-modification race aborts every remaining item (blocked:batch-aborted),
// because the ordering guarantee can no longer be trusted past that point.
func (s *ProofService) ApplyAmendDepsManifest(m *AmendDepsManifest) (*AmendDepsManifestReport, error) {
	m.EnsureOperationIDs()
	report := &AmendDepsManifestReport{SchemaVersion: AmendDepsManifestSchemaVersion}
	report.Items = make([]AmendDepsManifestStatus, 0, len(m.Items))
	aborted := false

	for _, item := range m.Items {
		if aborted {
			report.record(&AmendDepsManifestStatus{
				Node:        item.Node,
				OperationID: item.OperationID,
				Status:      "blocked:batch-aborted",
				Detail:      fmt.Sprintf("batch aborted before this item was attempted: %s", report.AbortReason),
				Reason:      item.Reason,
			})
			continue
		}

		req, parseErr := amendDepsRequestFromItem(item)
		if parseErr != nil {
			report.record(&AmendDepsManifestStatus{
				Node:        item.Node,
				OperationID: item.OperationID,
				Status:      rejectedStatus(parseErr),
				Detail:      parseErr.Error(),
				Reason:      item.Reason,
			})
			continue
		}

		result, err := s.AmendDeps(req.nodeID, req.req)
		if err != nil {
			status := rejectedStatus(err)
			record := AmendDepsManifestStatus{
				Node:        item.Node,
				OperationID: item.OperationID,
				Status:      status,
				Detail:      err.Error(),
				Reason:      item.Reason,
			}
			report.record(&record)
			if isConcurrentModification(err) {
				aborted = true
				report.Aborted = true
				report.AbortReason = err.Error()
			}
			continue
		}

		status := manifestStatusFromResult(item, result)
		report.record(&status)
		if status.Reverify {
			report.Reverify = append(report.Reverify, AmendDepsReverify{Node: status.Node, NewHash: status.NewHash, Reason: item.Reason})
		}
	}

	return report, report.exitError()
}

// operationRecordForEvent builds the operation-id binding for an event that
// has just been applied to st, matching what replay records. It lets a dry run
// recognise a repeated operation id exactly as the real run would.
func operationRecordForEvent(st *state.State, ev ledger.Event) state.OperationRecord {
	rec := state.OperationRecord{EventType: string(ev.Type())}
	if deps, ok := ev.(ledger.NodeDepsAmended); ok {
		rec.NodeID = deps.NodeID.String()
		rec.RequestFingerprint = deps.RequestFingerprint
		rec.PreviousHash = deps.PreviousContentHash
		rec.Reopened = deps.Reopened
		if n := st.GetNode(deps.NodeID); n != nil {
			rec.NewHash = n.ContentHash
		}
	}
	return rec
}

// planManifestItem validates one item against st without writing. It also
// returns the plan (including the event to append, if any) so the dry run can
// advance its in-memory state.
func (s *ProofService) planManifestItem(st *state.State, item AmendDepsManifestItem) (AmendDepsManifestStatus, depsPlan) {
	req, parseErr := amendDepsRequestFromItem(item)
	if parseErr != nil {
		return AmendDepsManifestStatus{
			Node: item.Node, OperationID: item.OperationID,
			Status: rejectedStatus(parseErr), Detail: parseErr.Error(), Reason: item.Reason,
		}, depsPlan{}
	}
	plan, err := planDepsAmendment(st, req.nodeID, req.req)
	if err != nil {
		status := rejectedStatus(err)
		// plan carries the attempted diff (if any) so the preview can show it.
		out := AmendDepsManifestStatus{
			Node: item.Node, OperationID: item.OperationID,
			Status: status, Detail: err.Error(), Reason: item.Reason,
		}
		out.OldHash = plan.Result.OldHash
		out.NewHash = plan.Result.NewHash
		out.Added = idStrings(plan.Result.Added)
		out.Removed = idStrings(plan.Result.Removed)
		out.AddedValidated = idStrings(plan.Result.AddedValidated)
		out.RemovedValidated = idStrings(plan.Result.RemovedValidated)
		return out, plan
	}
	return manifestStatusFromResult(item, plan.Result), plan
}

// manifestStatusFromResult converts a successful/unchanged/queued result into
// the manifest status vocabulary.
func manifestStatusFromResult(item AmendDepsManifestItem, result AmendDepsResult) AmendDepsManifestStatus {
	out := AmendDepsManifestStatus{
		Node:             item.Node,
		OperationID:      item.OperationID,
		Status:           result.Outcome,
		Seq:              result.Seq,
		OldHash:          result.OldHash,
		NewHash:          result.NewHash,
		Reopened:         result.Reopened,
		Reverify:         result.Reverify,
		Reason:           item.Reason,
		Added:            idStrings(result.Added),
		Removed:          idStrings(result.Removed),
		AddedValidated:   idStrings(result.AddedValidated),
		RemovedValidated: idStrings(result.RemovedValidated),
	}
	if result.Outcome == AmendDepsAppliedAlready {
		out.Status = "applied(already)"
	}
	return out
}

type amendDepsParsedRequest struct {
	nodeID types.NodeID
	req    AmendDepsRequest
}

// amendDepsRequestFromItem parses an item's node id and string lists into a
// typed request. A parse failure is a rejection, not a file-level error, so the
// rest of the manifest can still be processed.
func amendDepsRequestFromItem(item AmendDepsManifestItem) (amendDepsParsedRequest, error) {
	nodeID, err := types.Parse(item.Node)
	if err != nil {
		return amendDepsParsedRequest{}, fmt.Errorf("%w: invalid node %q: %v", ErrInvalidState, item.Node, err)
	}
	add, err := parseNodeIDs(item.Add)
	if err != nil {
		return amendDepsParsedRequest{}, err
	}
	remove, err := parseNodeIDs(item.Remove)
	if err != nil {
		return amendDepsParsedRequest{}, err
	}
	addVal, err := parseNodeIDs(item.AddValidated)
	if err != nil {
		return amendDepsParsedRequest{}, err
	}
	removeVal, err := parseNodeIDs(item.RemoveValidated)
	if err != nil {
		return amendDepsParsedRequest{}, err
	}
	return amendDepsParsedRequest{
		nodeID: nodeID,
		req: AmendDepsRequest{
			Add:             add,
			Remove:          remove,
			AddValidated:    addVal,
			RemoveValidated: removeVal,
			Reopen:          item.Reopen,
			ExpectHash:      item.ExpectHash,
			Strict:          item.Strict,
			Owner:           item.Owner,
			Reason:          item.Reason,
			OperationID:     item.OperationID,
		},
	}, nil
}

func parseNodeIDs(ids []string) ([]types.NodeID, error) {
	out := make([]types.NodeID, 0, len(ids))
	for _, s := range ids {
		id, err := types.Parse(s)
		if err != nil {
			return nil, fmt.Errorf("%w: invalid dependency id %q: %v", ErrInvalidState, s, err)
		}
		out = append(out, id)
	}
	return out, nil
}

// rejectedStatus renders an error as rejected:<code>. An un-coded error falls
// back to rejected:apply-error.
func rejectedStatus(err error) string {
	if code := aferrors.Code(err); code != 0 {
		return "rejected:" + code.String()
	}
	return "rejected:apply-error"
}

func isConcurrentModification(err error) bool {
	return aferrors.Code(err) == aferrors.VALIDATION_INVARIANT_FAILED
}

func idStrings(ids []types.NodeID) []string {
	if len(ids) == 0 {
		return nil
	}
	out := make([]string, len(ids))
	for i, id := range ids {
		out[i] = id.String()
	}
	return out
}

// generateDepsOperationID returns a fresh, ledger-safe operation id.
func generateDepsOperationID() string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("ad-%v", Now())
	}
	return "ad-" + hex.EncodeToString(b)
}
