// Package fs provides filesystem operations for the AF proof framework.
package fs

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
)

// InitProofDir initializes a proof directory structure at the given path.
// It creates the following directory structure:
//   - proof/           (root)
//   - proof/ledger/    (for event files)
//   - proof/nodes/     (for node JSON files)
//   - proof/defs/      (for definitions)
//   - proof/assumptions/ (for assumptions)
//   - proof/externals/ (for external references)
//   - proof/lemmas/    (for extracted lemmas)
//   - proof/locks/     (for node lock files)
//   - proof/meta.json  (configuration file)
//
// The function is idempotent: calling it multiple times on the same path
// will not cause errors or data loss. Existing files are preserved.
//
// Returns an error if the path is invalid or if directory creation fails
// due to permission issues or other filesystem errors.
func InitProofDir(path string) error {
	// Validate path
	if path == "" {
		return errors.New("path cannot be empty")
	}
	if strings.TrimSpace(path) == "" {
		return errors.New("path cannot be whitespace-only")
	}
	if strings.ContainsRune(path, '\x00') {
		return errors.New("path cannot contain null byte")
	}

	// Create the root proof directory
	if err := os.MkdirAll(path, 0755); err != nil {
		return err
	}

	// Create all subdirectories
	subdirs := []string{"ledger", "nodes", "defs", "assumptions", "externals", "lemmas", "locks"}
	for _, sub := range subdirs {
		subPath := filepath.Join(path, sub)
		if err := os.MkdirAll(subPath, 0755); err != nil {
			return err
		}
	}

	// Create meta.json if it doesn't exist
	metaPath := filepath.Join(path, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		content := []byte(`{"version": "1.0"}`)
		if err := os.WriteFile(metaPath, content, 0644); err != nil {
			return err
		}
	}

	// Drop a .gitignore for the workspace's runtime/rebuildable state so the
	// "track only source-of-truth" policy is the default everywhere. Preserve
	// any user-customised file (idempotent, like meta.json above).
	gitignorePath := filepath.Join(path, ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte(workspaceGitignore), 0644); err != nil {
			return err
		}
	}

	return nil
}

// workspaceGitignore is the default ignore file dropped into a proof workspace.
//
// Tracked (source of truth / filesystem-primary — commit these):
//   - ledger/      append-only event log, the single source of truth
//   - assumptions/ written directly to disk, not replayed from the ledger
//   - externals/   written directly to disk, not replayed from the ledger
//   - meta.json    workspace configuration
//
// Ignored: transient lock files and the pending-def request cache. The
// nodes/, defs/, and lemmas/ directories are also listed defensively; they are
// currently never written (fully derived from the ledger), so ignoring them is
// safe should a future materialisation cache start populating them.
const workspaceGitignore = `# af proof workspace — generated by ` + "`af init`" + `.
# Tracked (commit these): ledger/, assumptions/, externals/, meta.json.
# Everything below is runtime state or rebuildable from the ledger.
locks/
.af/
nodes/
defs/
lemmas/
`
